"""empty message

Revision ID: 01e496a2165f
Revises: 2412eaaab559
Create Date: 2018-08-07 18:28:43.355493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e496a2165f'
down_revision = '2412eaaab559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'possui_facebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('possui_facebook', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
