"""empty message

Revision ID: 2412eaaab559
Revises: 8bd6c7fb7e5b
Create Date: 2018-08-07 18:28:08.909814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2412eaaab559'
down_revision = '8bd6c7fb7e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('texto', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    op.add_column('usuario', sa.Column('possui_facebook', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'possui_facebook')
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('texto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], [u'usuario.id'], name=u'feedback_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'feedback_pkey')
    )
    op.drop_table('contato')
    # ### end Alembic commands ###
