"""empty message

Revision ID: a0f4de25011d
Revises: 8eb7d569652e
Create Date: 2018-12-12 11:05:14.241292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f4de25011d'
down_revision = '8eb7d569652e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anuncio', sa.Column('cidade_veiculo', sa.String(), nullable=True))
    op.add_column('anuncio', sa.Column('estado_veiculo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anuncio', 'estado_veiculo')
    op.drop_column('anuncio', 'cidade_veiculo')
    # ### end Alembic commands ###
