"""empty message

Revision ID: a2341e78e660
Revises: 01e496a2165f
Create Date: 2018-08-15 14:42:29.271457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2341e78e660'
down_revision = '01e496a2165f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anuncio', sa.Column('aprovado_em', sa.DateTime(), nullable=True))
    op.add_column('anuncio', sa.Column('criado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anuncio', 'criado_em')
    op.drop_column('anuncio', 'aprovado_em')
    # ### end Alembic commands ###
